### ISSUE TITLE
Where 'phone_fields' come from?

### ISSUE THREAD

**Issue by ReCodeRa** [redamarzouk/Scraping_Agent#2]
Where should this field originate?
_An error occurred: name 'phone_fields' is not defined_
Regardless, thank you for the cool code :)))

**Comment by redamarzouk** [comment]
Hello I've had an optional parameter phone_fields that is not defined, i've just pushed a new version.
you just need to delete the phone_fileds parameter in line 134.

**Comment by ReCodeRa** [comment]
Thanks for your response :) SOLVED :)

**Comment by ReCodeRa** [comment]
Thanks for response. SOLVED :)
